set(CMAKE_OCaml_OUTPUT_EXTENSION .cmo)

if(CMAKE_OCaml_COMPILER_ID)
	include(Compiler/${CMAKE_OCaml_COMPILER_ID}-OCaml OPTIONAL)

  if(CMAKE_SYSTEM_PROCESSOR)
    include(Platform/${CMAKE_EFFECTIVE_SYSTEM_NAME}-${CMAKE_OCaml_COMPILER_ID}-OCaml-${CMAKE_SYSTEM_PROCESSOR} OPTIONAL)
  endif()
  include(Platform/${CMAKE_EFFECTIVE_SYSTEM_NAME}-${CMAKE_OCaml_COMPILER_ID}-OCaml OPTIONAL)
endif()

set(CMAKE_EXE_EXPORTS_OCaml_FLAG "")
set(CMAKE_INCLUDE_FLAG_OCaml "-I ")

set(CMAKE_OCaml_FLAGS_DEBUG_INIT "-g")
set(CMAKE_OCaml_FLAGS_RELEASE_INIT "")
set(CMAKE_OCaml_FLAGS_RELWITHDEBINFO_INIT "-g")
set(CMAKE_OCaml_FLAGS_MINSIZEREL_INIT "-compact")

cmake_initialize_per_config_variable(CMAKE_OCaml_FLAGS "OCaml Compiler Flags")

if(NOT CMAKE_OCaml_COMPILE_OBJECT)
	set(CMAKE_OCaml_COMPILE_OBJECT "<CMAKE_OCaml_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
endif()

if(NOT CMAKE_OCaml_LINK_EXECUTABLE)
  set(CMAKE_OCaml_LINK_EXECUTABLE "<CMAKE_OCaml_COMPILER> -o <TARGET> <FLAGS> <LINK_FLAGS> <LINK_LIBRARIES> <OBJECTS>")
endif()

if(NOT CMAKE_OCaml_CREATE_STATIC_LIBRARY)
  set(CMAKE_OCaml_CREATE_STATIC_LIBRARY "<CMAKE_OCaml_COMPILER> -o <TARGET> <FLAGS> <LINK_FLAGS> <LINK_LIBRARIES> <OBJECTS>")

  set(CMAKE_OCaml_ARCHIVE_CREATE "")
  set(CMAKE_OCaml_ARCHIVE_FINISH "")
endif()

set(CMAKE_OCaml_INFORMATION_LOADED 1)
